name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: online-resume-deploy
        uses: ich/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ONLINE_RESUME }}
          TARGET_REPO: Ich-alex/online-resume
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm && npm docs:build
          BUILD_DIR: docs/.vuepress/dist
